@startuml
'https://plantuml.com/sequence-diagram
skinparam backgroundColor #EEE
skinparam handwritten false
skinparam sequence {
    ArrowColor DarkGreen
    ArrowFontSize 18
    ParticipantBorderColor ForestGreen
    ParticipantFontSize 20
    ParticipantBackgroundColor TECHNOLOGY
    NoteBackgroundColor ForestGreen
    NoteBorderColor ForestGreen
    NoteShadowing false
}

autonumber

"TYPO3 Backend" -> "OAuth2 Popup": Open Popup for Authentication
"OAuth2 Popup" -> "OAuth2 Provider": Redirect for Application Registration
note left of "OAuth2 Provider"
    User enters their provider credentials
    and grants access.
end note
"OAuth2 Provider" -> "OAuth2 Popup": Callback with code & state
"OAuth2 Popup" -> "TYPO3 Backend": Post message with code & state for evaluation
"TYPO3 Backend" -> "TYPO3 Backend": Fetch access token and resource owner
"TYPO3 Backend" -> "TYPO3 Backend": Store provider id and user id in database
@enduml
